### ISSUE TITLE
Does the app need the INTERNET permission?

### ISSUE THREAD

**Issue by matchboxbananasynergy** [ImranR98/Circular-Video-Recorder#2]
Hey there! I just downloaded your app to check it out, and it's quite neat.

I noticed, however, that the app declares the `INTERNET` permission (https://github.com/ImranR98/Circular-Video-Recorder/blob/main/android/app/src/main/AndroidManifest.xml#L3). Is there a reason for that?

I saw that in the latest version, the "server" functionality was stripped out (unsure what that means). Is it possible that this permission is unneeded?

**Comment by ImranR98** [comment]
The server function would create an http server so the user could access recordings through other devices on their network. Decided to remove it as it was http (no encryption) and had no login/auth, and I never used it (didn't think anyone else uses this app lmao).

You're right, I forgot to remove the internet permission which is no longer needed.
